server:
  port: 9191
spring:
  application:
    name: msvc-catalog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalogdb
    username: leo
    password: sqlLeo02
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  config:
    import: optional:configserver:http://localhost:8888




